version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - /home/lyes/MAHAD_PROJECT/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - kafka_net

  mqtt-kafka-connector:
    image: arthurescriou/mqtt-kafka-connector:1.0.0
    container_name: mqtt-kafka-connector
    restart: on-failure
    environment:
      BROKER_1: kafka:9092
      BROKER_2: kafka:9092
      BROKER_3: kafka:9092
      KAFKA_TOPIC: stock
      MQTT_TOPIC: topic
      MQTT_ENDPOINT: ws://mosquitto:1883
    networks:
      - kafka_net

volumes:
  mosquitto_data:
  mosquitto_log:

networks:
  kafka_net:
    external: true
    name: Kafka_net
